### ISSUE TITLE
Case studies for Open Source exercise

### ISSUE THREAD

**Issue by malvikasharan** [The-Turing-Summer-Experience/intro-to-github#3]
We have 5 case studies of open source projects.
All the case studies can be found here:  https://docs.google.com/document/d/1ymSkxDFTi2vyVtX_iTAqZuj8g16EIhXGvWN3CZ2OowM/edit

Please select one case study and answer these questions:
- What is the project’s license?
- Why do you think this license benefits this project?
- What platform do they host their code on?

**Comment by malvikasharan** [comment]
When you are ready, add your notes under your assigned group number: https://github.com/The-Turing-Summer-Experience/intro-to-github/blob/main/github-workshop/introductions-2024-session-1.md

**Comment by aleesteele** [comment]
Woohoo! Looks like it went well 😄 Closing this for now ❤️ - thanks @malvikasharan !
